/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application.views;

import application.dao.CandidateDao;
import application.daoimpl.CandidateDaoImpl;
import application.models.CandidateModel;
import application.models.CandidateTableModel;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mhdja
 */
public class AlternatifView extends javax.swing.JPanel {
     private final CandidateDao candidateDao;
    /**
     * Creates new form AlternatifView
     */
    public AlternatifView() {
        this.candidateDao = new CandidateDaoImpl();
        initComponents();
        
        this.LoadData();
    }
    
    public void LoadData() {
        List<CandidateModel> candidates = this.candidateDao.findAll();

        // Buat kolom untuk tabel
        String[] columnNames = {"Nama", "Nilai Kepemimpinan", "Pengetahuan", "Kemampuan Teknis", "Kemampuan Lanjutan"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        // Isi tabel dengan data kandidat
        for (CandidateModel candidate : candidates) {
            Object[] rowData = {
                candidate.getName(),
                candidate.getLeadershipScore(),
                candidate.getKnowledgeScore(),
                candidate.getTechnicalSkillScore(),
                candidate.getAdvancedSkillScore()
            };
            model.addRow(rowData);
        }

        // Tampilkan di JTable
        jTable1.setModel(model);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        title.setBackground(new java.awt.Color(168, 140, 59));
        title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Data Alternatif");
        title.setOpaque(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
